services:
  - type: web
    name: korochki-net
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn korochki_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: korochki-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
